feat: Add Git commit (#6)
* feat: Add git commit

* ci: Fix import/named problem

https://stackoverflow.com/questions/55198502/using-eslint-with-typescript-unable-to-resolve-path-to-module

* feat: Add bootstrap code

* test: Add simple-git config information

* ci: Rename job of CI workflow

* refactor: Reorganize directory structure

* ci: Add local test

* build: Update artifact

* fix: Remove Git config

* refactor: Separate env

---------

Co-authored-by: whatasame <whatasame@users.noreply.github.com>

diff --git a/.github/workflows/local-test.yml b/.github/workflows/local-test.yml
--- a/.github/workflows/local-test.yml
+++ b/.github/workflows/local-test.yml
@@ -12,3 +12,13 @@ jobs:
       - name: Test local action
         id: test-action
         uses: ./
+
+      - name: Check if '__post' directory exists
+        id: check-post-directory
+        run: |
+          if [ -d "__post" ]; then
+            echo "Success: '__post' directory exists."
+          else
+            echo "Error: '__post' directory not found."
+            exit 1
+          fi
