fix: Add workflow inputs

diff --git a/.github/workflows/local-test.yml b/.github/workflows/local-test.yml
--- a/.github/workflows/local-test.yml
+++ b/.github/workflows/local-test.yml
@@ -12,6 +12,19 @@ jobs:
       - name: Test local action
         id: test-action
         uses: ./
+        with:
+          notion_api_key: ${{ secrets.NOTION_API_KEY }}
+          notion_database_id: ${{ secrets.NOTION_DATABASE_ID }}
+
+      - name: Check if '__post' directory exists
+        id: check-post-directory
+        run: |
+          if [ -d "__post" ]; then
+            echo "Success: '__post' directory exists."
+          else
+            echo "Error: '__post' directory not found."
+            exit 1
+          fi
 
       - name: Check if '__post' directory exists
         id: check-post-directory
